## In this course
- Data analysis: use mostly known (to you) statistical methods to gain
insight about data.
- Use two software packages, SAS and R — I assume you know nothing
about these.
- Look at lots of examples.
- “Get your hands dirty”.
- Writing reports.
- Other tasks in R and SAS.

## Prerequisites xxx check for C32/C33

- You need a second Statistics course that covers statistical inference,
one of:
- STAB57 (or equivalent such as STA 261, STA 248)
- STAB27 (or equivalent such as MGEB12, PSYC08, STA 221)
- I check prerequisites.

## The instructor
- Ken Butler, office IC 471, e-mail:
mailto:butler@utsc.utoronto.ca
- Lectures: both of Tuesday 13:00-14:00 in SW 309, Thursday
12:00-13:00 in SW 319. Tutorial: one of Wednesday 10:00-11:00,
11:00-12:00, 15:00-16:00 or 16:00-17:00 in BV 498.
- Office hours: Tuesday 14:00-15:30, Thursday 10:30-11:30. I am likely
also around on Monday. Or by appointment (e-mail me, address
above, to set one up).
- This course is on Quercus. Go to q.utoronto.ca, log in, and find
this course among your courses. Assignment hand-in, grading and
marks will be done through Quercus. xxx course website
- E-mail: Use only UTSC/UToronto e-mail address. I aim to respond
within two working days. Non-simple questions: office hours/tutorial.

## Text(s) xxx grab pictures
Recommended:
- “SAS Essentials: Mastering SAS for
data analytics” by Alan C. Elliott and
Wayne A. Woodward, publ. Wiley.
ISBN 978-1-119-04216-7.
- “R for Data Science” by Hadley
Wickham and Garrett Grolemund, publ.
O’Reilly, ISBN 978-1-491-91039-9. Also
available (free) online 
[here](http://r4ds.had.co.nz/).

## Structure of course
- 3 hours/week of class time.
- Of these, 1 hour in computer lab (“tutorial”):
- practice what you learned from lecture
- I give you lab exercises to work on, with answers, or you can work on
your assignment.
- Get help if needed (instructor/TA available)

## Course material
For each of R (first) and then SAS:
- Installation / connection
- Reading data files (of different sorts)
- Making graphs
- Numerical summaries
- Statistical inference
- Reports
- Tidying and organizing data
- Case studies
- Functions / arrays
- Dates and times
- Miscellaneous tasks
- Vector-matrix algebra (if time permits)

## Laptop use
- If you have a laptop, you may find it useful for following along with
the use of the software or for taking notes.
- Checking social media or other non-course-specific activity during
class distracts from your learning. If you are going to get the most
from this course, you need to pay full attention in class. Multi-tasking
will not help you.
- Using your laptop for non-course activity will also distract those
around you and creates a worse learning experience for everybody. If
somebody’s inappropriate laptop use is distracting you, let me know. I
will create laptop-free zones in class if necessary.

## Assessment

xxx include latex table here

## Open book, defined
“Open book” means these are permissible, written/printed versions only:
- the SAS text
- the R text
- my lecture notes
- assignments, yours (graded) and mine (with solutions)
- any other notes that you have made in this course.

Old exams are not permitted.

## Missed work and documentation
- No make-up assignments or tests in this course.
- Work handed in late may or may not be accepted (instructor’s
discretion; instructor’s decision is final).
- If you miss assessed work due to illness/injury, complete form 
{here}(http://www.illnessverification.utoronto.ca/)
and submit to instructor within 10 working days of due date.
- Weight of missed work with appropriate documentation transferred to
other assessments of same type.

## Academic integrity
- Read and understand 
[this][http://www.utoronto.ca/academicintegrity/]
- Academic dishonesty devalues your degree and those of all other
students.
- Cheating and plagiarism taken very seriously.
- Examples of academic offences:
- Using someone else’s words/ideas without acknowledgement.
- Obtaining or providing unauthorized assistance on an assignment.
- On test/exam, looking at someone else’s answers or allowing someone
else to look at yours.
- Pretending to be someone else.
- Falsifying or altering required documentation (eg. doctor’s notes).

## Penalties
- Penalties include (depending on seriousness of offence) a mark of zero
for the work concerned, a mark of zero for the entire course, or
suspension/expulsion from the University.
- Penalties are (much) more severe for those caught a second (or third)
time.
- “Students who cheat and are not caught will be haunted by the
memory of their misdeeds for the rest of their miserable lives.” (From 
[here](https://philosophy.osu.edu/sites/philosophy.osu.edu/files/1100%20Brown_2.pdf).)

## Accessibility statement
Students with diverse learning styles and needs are welcome in this
course. In particular, if you have a disability/health consideration
that may require accommodations, please feel free to approach
me and/or the AccessAbility Services Office as soon as possible.
I will work with you and AccessAbility Services to ensure you can
achieve your learning goals in this course. Enquiries are confiden-
tial. The UTSC AccessAbility Services staff (located in S302) are
available by appointment to assess specific needs, provide referrals
and arrange appropriate accommodations: (416) 287-7560 or by
e-mail at `ability@utsc.utoronto.ca`.

