/*
 This file is auto-generated by the statrep package.
 Do not edit this file or your changes will be lost.
 Edit the LaTeX file instead.
 
 See the statrep package documentation and the file
 statrep.cfg for information on these settings.
 */
 
 
%include "./slides-sas_SR_preamble.sas" /nosource;
/* Remove all output files. */
%cleandir(., tex, tex);
%cleandir(., png, png);
%cleandir(., lst, lst);


/* Start program with a null title. */
title;

proc import
  datafile='/home/ken/test1.csv'
  dbms=csv
  out=mydata
  replace;
  getnames=yes;

%output(ra)
proc print;

%endoutput(ra)

%output(rb)
proc means;
    
%endoutput(rb)

%write(rbb,store=rb,type=listing) 

%output(ua)
filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/global.csv";

proc import
  datafile=myurl
  dbms=csv
  out=global
  replace;
  getnames=yes;

proc print;
    
%endoutput(ua)

%write(uaa,store=ua,type=listing) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/coffee.txt";
proc import
  datafile=myurl
  dbms=dlm
  out=coffee
  replace;
  delimiter=' ';
  getnames=yes;


%output(rc)
proc print data=coffee(obs=15);
    
%endoutput(rc)

%write(rcc,store=rc,type=listing) 

%output(ub)
filename myurl
 url
 "http://www.utsc.utoronto.ca/~butler/c32/soap.txt";

proc import
  datafile=myurl
  dbms=dlm
  out=soap
  replace;
  delimiter=' ';
  getnames=yes;

proc print data=soap(obs=10);

  
%endoutput(ub)

%write(ubb,store=ub,type=listing) 

proc import
  datafile='/home/ken/test2.xlsx'
  dbms=xlsx
  out=mydata
  replace;
  sheet=data;
  getnames=yes;


%output(re)
proc print;
  
%endoutput(re)

%write(ree,store=re,type=listing) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/ais.txt";
proc import
  datafile=myurl
  dbms=dlm
  out=sports
  replace;
  delimiter='09'x;
  getnames=yes;



%output(ga)
proc print data=sports(obs=9);
  
%endoutput(ga)

%write(gaa,store=ga,type=listing) 

%output(gb)
proc means;
  
%endoutput(gb)

%write(gbb,store=gb,type=listing) 

%output(gd)
proc sgplot;
  vbar Sport;
  
%endoutput(gd)

%write(gdd,store=gd,type=graphic) 

%output(ge)
proc sgplot;
  histogram BMI;
  
%endoutput(ge)

%write(gee,store=ge,type=graphic) 

%output(gf)
proc sgplot;
  vbar Sport / group=Sex groupdisplay=cluster;
  
%endoutput(gf)

%write(gff,store=gf,type=graphic) 

%output(gg)
proc sgplot;
  vbox BMI / category=Sex;
  
%endoutput(gg)

%write(ggg,store=gg,type=graphic) 

%output(gh)
proc sgplot;
  scatter x=Ht y=Wt;
  
%endoutput(gh)

%write(ghh,store=gh,type=graphic) 

%output(gj)
proc sgplot;
  scatter x=Ht y=Wt;
  reg x=Ht y=Wt;
  
%endoutput(gj)

%write(gjj,store=gj,type=graphic) 

%output(gi)
proc sgplot;
  vbox BMI / group=Sex category=Sport;
  
%endoutput(gi)

%write(gii,store=gi,type=graphic) 

%output(gk)
proc sgplot;
  scatter x=Ht y=Wt / group=Sex;
  
%endoutput(gk)

%write(gkk,store=gk,type=graphic) 

%output(gl)
proc sgpanel;
  panelby Sport;
  scatter x=Ht y=Wt / group=Sex;
  
%endoutput(gl)

%write(gll,store=gl,type=graphic) 

data ath;
  set sports;


%output(sa)
proc means Q1 Q3 Qrange;
  var Wt;
  
%endoutput(sa)

%write(saa,store=sa,type=listing) 

%output(sb)
proc means mean stddev;
  var Ht;
  class Sex;
    
%endoutput(sb)

%write(sbb,store=sb,type=listing) 

%output(sc)
proc means n;
  var BMI;
  class Sport;
    
%endoutput(sc)

%write(scc,store=sc,type=listing) 

%output(sd)
proc freq;
  tables Sport;
  
%endoutput(sd)

%write(sdd,store=sd,type=listing) 

%output(se)
proc means stddev;
    
%endoutput(se)

%write(see,store=se,type=listing) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/jays15-home.csv";
proc import
  datafile=myurl
    dbms=csv
    out=jays
    replace;
  getnames=yes;


%output(iza)
proc print data=jays(obs=6);
    
%endoutput(iza)

%write(izaa,store=iza,type=listing) 

%output(ia)
proc ttest h0=29327;
  var attendance;
  
%endoutput(ia)

%write(iaa,store=ia,type=listing) 

%output(id)
  proc sgplot;
    vbox attendance / category=daynight;

%endoutput(id)

%write(idd,store=id,type=graphic) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/drp.txt";
proc import
  datafile=myurl
  dbms=dlm
  out=reading
  replace;
  delimiter=' ';
  getnames=yes;

%output(ix)
  proc print;

%endoutput(ix)

%write(ixx,store=ix,type=listing) 

%output(if)
  proc means;
    class group;
    var score;

%endoutput(if)

%write(iff,store=if,type=listing) 

%output(ifx)
  proc sgplot;
    vbox score / category=group;

%endoutput(ifx)

%write(ifxx,store=ifx,type=graphic) 

%output(ihy)
  proc ttest side=L;
    var score;
    class group;

%endoutput(ihy)

%write(ihyy,store=ihy,objects=ttests,type=listing) 

%output(pb)
proc power;
  onesamplemeans
  test=t
  nullmean=10
  mean=8
  stddev=4
  ntotal=15
  power=.;
    
%endoutput(pb)

%write(pbb,store=pb,type=listing) 

%output(pc)
proc power;
  onesamplemeans
  test=t
  nullmean=10
  mean=8
  stddev=4
  ntotal=.
  power=0.80;
    
%endoutput(pc)

%write(pcc,store=pc,type=listing) 

%output(pd)
  proc power plotonly;
    onesamplemeans
      test=t
      nullmean=10
      mean=8
      stddev=4
      ntotal=15
      power=.;
    plot x=n min=15 max=80;
  
%endoutput(pd)

%write(pdd,store=pd,type=graphic) 

%output(pe)
  proc power plotonly;
    onesamplemeans
      test=t
      nullmean=10
      mean=8
      stddev=4
      ntotal=15 34
      power=.;
    plot x=effect min=5 max=10;
  
%endoutput(pe)

%write(pee,store=pe,type=graphic) 

%output(ph)
proc means;
  var score;
  class group;

%endoutput(ph)

%write(phh,store=ph,type=listing) 

%output(pf)
  proc power plotonly;
    twosamplemeans
      test=diff_satt
      sides=1
      meandiff=5 10
      stddev=15
      ntotal=44
      power=.;
    plot x=n min=10 max=300;
  
%endoutput(pf)

%write(pff,store=pf,type=graphic) 

%output(il)
  proc power;
  twosamplemeans
    test=diff_satt
    sides=1
    meandiff=5
    groupstddevs=11|17
    groupns=21|23
    power=.;

%endoutput(il)

%write(ill,store=il,type=listing) 

%output(im)
  proc power;
  twosamplemeans
    test=diff_satt
    sides=1
    meandiff=5
    stddev=15
    groupns=10|34
    power=.;

%endoutput(im)

%write(imm,store=im,type=listing) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/duality.txt";
proc import
  datafile=myurl
    dbms=dlm
    out=duality
    replace;
  delimiter=' ';
  getnames=yes;


%output(it)
proc print;
  
%endoutput(it)

%write(itt,store=it,type=listing) 

%output(iu)
    proc ttest;
      var y;
      class group;
  
%endoutput(iu)

%write(iuu,store=iu,objects=conflimits ttests,type=listing) 

%output(iva)
    proc ttest alpha=0.10;
      var y;
      class group;
  
%endoutput(iva)

%write(ivaa,store=iva,objects=conflimits ttests,type=listing) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/irs.txt";
proc import
  datafile=myurl
    dbms=csv
    out=irs
    replace;
  getnames=yes;


%output(ij)
proc print;
  
%endoutput(ij)

%write(ijj,store=ij,type=listing) 

%output(ik)
proc ttest h0=160 sides=U;
  var Time;
  
%endoutput(ik)

%write(ikk,store=ik,type=listing) 

%output(il)
proc sgplot;
  histogram Time;
    
%endoutput(il)

%write(ill,store=il,type=graphic) 

%output(im)
proc univariate location=160;
  var Time;
    
%endoutput(im)

%write(imm,store=im,objects=testsforlocation,type=listing) 

%output(in)
proc sgplot;
  vbox Time;
    
%endoutput(in)

%write(inn,store=in,type=graphic) 

%output(pevay)
proc univariate cipctldf;
  var Time;
    
%endoutput(pevay)

%write(pevayy,store=pevay,objects=quantiles,type=listing) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/analgesic.txt";
proc import
  datafile=myurl
    dbms=dlm
    out=pain
    replace;
  delimiter=' ';
  getnames=yes;

%output(iz)
proc print;
  
%endoutput(iz)

%write(izz,store=iz,type=listing) 

%output(ic)
proc ttest;
  paired druga*drugb;

%endoutput(ic)

%write(icc,store=ic,type=listing) 

data pain2;
  set pain;
  diff=druga-drugb;

%output(iy)
proc print;
  
%endoutput(iy)

%write(iyy,store=iy,type=listing) 

%output(id)
  proc ttest h0=0;
    var diff;

%endoutput(id)

%write(idd,store=id,type=listing) 

%output(ie)
  proc univariate noprint;
    qqplot diff;

%endoutput(ie)

%write(iee,store=ie,type=graphic) 

%output(if)
  proc univariate noprint;
    qqplot diff / normal(mu=est sigma=est);

%endoutput(if)

%write(iff,store=if,type=graphic) 

%output(ig)
  proc univariate noprint;
    qqplot diff / normal(mu=-1.65 sigma=1.455);

%endoutput(ig)

%write(igg,store=ig,type=graphic) 

%output(ihx)
proc univariate;
  var diff;

%endoutput(ihx)

%write(ihxx,store=ihx,objects=TestsforLocation,type=listing) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/drp.txt";
proc import
  datafile=myurl
  dbms=dlm
  out=reading
  replace;
  delimiter=' ';
  getnames=yes;

%output(iw)
  proc print;

%endoutput(iw)

%write(iww,store=iw,type=listing) 

%output(iv)
proc npar1way median;
  var score;
  class group;
  
%endoutput(iv)

%write(ivw,store=iv,objects=medianScores,type=listing) 

%write(ivv,store=iv,objects=medianTest medianAnalysis,type=listing) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/jumping.txt";
proc import
  datafile=myurl
    dbms=dlm
    out=rats
    replace;
  delimiter=' ';
  getnames=yes;

%output(ih)
proc anova;
  class group;
  model density=group;

%endoutput(ih)

%write(ihh,store=ih,objects=OverallANOVA ModelANOVA,type=listing) 

%output(ii)
proc anova;
  class group;
  model density=group;
  means group / tukey;

%endoutput(ii)

%write(iii,store=ii,objects=MCLines,type=listing) 

%output(ja)
proc npar1way median;
  var density;
  class group;
  
%endoutput(ja)

%write(jaa,store=ja,objects=medianScores,type=listing) 

%write(jab,store=ja,objects=medianAnalysis,type=listing) 

%output(jc)
proc anova;
  class group;
  model density=group;
  means group / hovtest=levene welch;

%endoutput(jc)

%write(jcc,store=jc,objects=Welch Means,type=listing) 

%output(rugap)
proc mixed;
  class group;
  model density=group / ddfm=satterth;
  repeated / group=group;
  lsmeans group / adjust=tukey adjdfe=row;
    
%endoutput(rugap)

%write(rugapp,store=rugap,objects=diffs,type=listing) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/ais.txt";
proc import
  datafile=myurl
  dbms=dlm
  out=sports
  replace;
  delimiter='09'x;
  getnames=yes;



%output(ta)
proc print data=sports(obs=10);
  
%endoutput(ta)

%write(taa,store=ta,type=listing) 

data sports2;
  set sports;
  keep Sport Sex Ht Wt;


%output(tb)
proc print data=sports2(obs=8);
  
%endoutput(tb)

%write(tbb,store=tb,type=listing) 

data sports3;
  set sports;
  drop RCC--LBM;


%output(tc)
    proc print data=sports3(obs=8);
  
%endoutput(tc)

%write(tcc,store=tc,type=listing) 

data sports4;
  set sports;
  Wt_lb=Wt*2.2;
  keep Sport Wt Wt_lb;


%output(td)
proc print data=sports4(obs=7);
  
%endoutput(td)

%write(tdd,store=td,type=listing) 

data sports5;
  set sports;
  if _N_>=16 and _N_<=25;

%output(te)
proc print;

%endoutput(te)

%write(tee,store=te,type=listing) 

data sports6;
  set sports;
  if _N_ in (10, 13, 17, 42);


%output(tf)
proc print;
  
%endoutput(tf)

%write(tff,store=tf,type=listing) 

data sports7;
  set sports;
  if Sport="Tennis";


%output(tg)
proc print;
  
%endoutput(tg)

%write(tgg,store=tg,type=listing) 

data sports8;
  set sports;
  if Sport="Tennis" and RCC<5;


%output(th)
proc print;
  var Sex--RCC;
  
%endoutput(th)

%write(thh,store=th,type=listing) 

data sports9;
  set sports;
  if Sport="Tennis" or RCC>5;


%output(ti)
proc print;
  var Sex--RCC BMI;
  
%endoutput(ti)

%write(tii,store=ti,type=listing) 

%output(zawis)
proc means;
  where sport="Tennis";
  var BMI;
    
%endoutput(zawis)

%write(zawiss,store=zawis,type=listing) 

%output(tj)
proc sort data=sports;
  by RCC;

proc print;
  var Sex--RCC;
  
%endoutput(tj)

%write(tjj,store=tj,type=listing) 

%output(tk)
proc sort data=sports;
  by RCC BMI;

proc print;
  var Sex--RCC BMI;
  
%endoutput(tk)

%write(tkk,store=tk,type=listing) 

%output(tl)
proc sort data=sports;
  by descending BMI;

proc print;
  var Sex--RCC BMI;
  
%endoutput(tl)

%write(tll,store=tl,type=listing) 

%output(tm)
proc sort data=sports;
  by descending Wt;

data sports10;
  set sports;
  if _N_<=7;
  keep Sport Wt;

proc print;
  
%endoutput(tm)

%write(tmm,store=tm,type=listing) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/pigs1.txt";
proc import
  datafile=myurl
  dbms=dlm out=pigs replace;
  delimiter=' ';
  getnames=yes;


%output(tn)
proc print;
    
%endoutput(tn)

%write(tnn,store=tn,type=listing) 

data pigs2;
  set pigs;
  feed='feed1';
  weight=feed1;
  output;
  feed='feed2';
  weight=feed2;
  output;
  feed='feed3';
  weight=feed3;
  output;
  feed='feed4';
  weight=feed4;
  output;
  keep feed weight;


%output(to)
proc print;
  
%endoutput(to)

%write(too,store=to,type=listing) 

data pigs3;
  set pigs;
  array feed_array [4] feed1-feed4;
  do i=1 to 4;
    weight=feed_array[i];
    feed=vname(feed_array[i]);
    output;
  end;
  keep pig feed weight;


%output(tp)
proc print;
  
%endoutput(tp)

%write(tpp,store=tp,type=listing) 

%output(tr)
proc anova;
  class feed;
  model weight=feed;
  means feed / tukey;
  
%endoutput(tr)

%write(trs,store=tr,objects=overallanova modelanova,type=listing) 

%write(trr,store=tr,objects=mclines,type=listing) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/global.csv";
proc import
    datafile=myurl
    dbms=dlm
    out=util
    replace;
    delimiter=' ';
    getnames=yes;


%output(ca)
proc print data=util(obs=8);
  
%endoutput(ca)

%write(caa,store=ca,type=listing) 

%output(dda)
proc sgplot;
  scatter x=usage y=demand;
    
%endoutput(dda)

%write(ddaa,store=dda,type=graphic) 

%output(ddb)
proc reg;
  model demand=usage;
    
%endoutput(ddb)

%write(ddbb,store=ddb,objects=FitStatistics ParameterEstimates,type=listing) 

%write(ddbd,store=ddb,objects=diagnosticspanel,type=graphic) 

%write(ddbe,store=ddb,objects=residualplot,type=graphic) 

%output(dde)
proc transreg;
  model boxcox(demand)=identity(usage);
    
%endoutput(dde)

%write(ddef,store=dde,type=graphic) 

data trans;
  set util;
  rtdemand=sqrt(demand);

%output(ddf)
proc sgplot;
  scatter x=usage y=rtdemand;

%endoutput(ddf)

%write(ddff,store=ddf,type=graphic) 

%output(ddg)
proc reg;
  model rtdemand=usage;
    
%endoutput(ddg)

%write(ddgg,store=ddg,objects=FitStatistics ParameterEstimates,type=listing) 

%write(ddhh,store=ddg,objects=diagnosticspanel,type=graphic) 

%write(ddii,store=ddg,objects=fitplot,type=graphic) 

%output(muber)
filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/pigs.txt";
proc import
  datafile=myurl
  out=pigs
  dbms=dlm
  replace;
  getnames=yes;
  delimiter=' ';

proc print;
    
%endoutput(muber)

%write(muberr,store=muber,type=listing) 

%output(kogep)
proc glm;
  class feed;
  model weight=feed / solution;
    
%endoutput(kogep)

%write(kogepp,store=kogep,objects=overallanova modelanova#2 parameterestimates,type=listing) 

%output(siqet)
filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/crickets2.csv";
proc import
  datafile=myurl
  out=crickets
  dbms=csv
  replace;
  getnames=yes;

proc print data=crickets(obs=20);
    
%endoutput(siqet)

%write(siqett,store=siqet,type=listing) 

%output(zereq)
proc glm;
  class species;
  model pulse_rate=temperature species / solution;
    
%endoutput(zereq)

%write(zereqq,store=zereq,objects=overallANOVA,type=listing) 

%write(zereqr,store=zereq,objects=modelANOVA#2,type=listing) 

%write(zereqt,store=zereq,objects=parameterestimates,type=listing) 

%write(zereqs,store=zereq,objects=ancovaplot,type=graphic) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/mydates.csv";
proc import
  datafile=myurl
    dbms=csv
    out=dates
    replace;
  getnames=yes;


%output(da)
proc print;
  
%endoutput(da)

%write(daa,store=da,type=listing) 

%output(db)
proc print;
  format date mmddyy8.;
  
%endoutput(db)

%write(dbb,store=db,type=listing) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/pieces.txt";
proc import
  datafile=myurl
    dbms=dlm
    out=pieces
    replace;
  delimiter=' ';
  getnames=yes;

data makedates;
  set pieces;
  sasdate=mdy(month,day,year);


%output(dd)
proc print;
  format sasdate yymmdd10.;
    
%endoutput(dd)

%write(ddd,store=dd,type=listing) 

%output(dda)
proc print;
    
%endoutput(dda)

%write(ddda,store=dda,type=listing) 

%output(jahaq)
filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/monthly.csv";
proc import
  datafile=myurl
  out=sales1
  dbms=csv
  replace;
  getnames=yes;

proc print;
    
%endoutput(jahaq)

%write(jahaqq,store=jahaq,type=listing) 

%output(nubiv)
data sales2;
  set sales1;
  date_text=cat('16 ',month,' ',year);
  real_date=input(date_text,anydtdte20.);

proc print;
  var sales date_text real_date;
  format real_date yymmdd10.;
    
%endoutput(nubiv)

%write(nubivv,store=nubiv,type=listing) 

%output(komav)
proc sgplot;
  series x=real_date y=sales / markers;
  format real_date monyy7.;
  
%endoutput(komav)

%write(komavv,store=komav,type=graphic) 

%output(dm)
proc print data=dates;

%endoutput(dm)

%write(dmm,store=dm,type=listing) 

data moredates;
  set dates;
  d=day(date);
  m=month(date);
  y=year(date);

%output(dn)
proc print;

%endoutput(dn)

%write(dnn,store=dn,type=listing) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/dt.csv";
proc import
  datafile=myurl
    dbms=csv
    out=dt
    replace;
  getnames=yes;

%output(do)
proc print;

%endoutput(do)

%write(doo,store=do,type=listing) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/manypieces.txt";
proc import
  datafile=myurl
    dbms=dlm
    out=many
    replace;
  delimiter=' ';
  getnames=yes;


data dtm;
  set many;
  thedate=mdy(month,day,year);
  sasdt=dhms(thedate,hour,minute,second);
  keep thedate hour minute second sasdt;


%output(qa)
proc print;
  
%endoutput(qa)

%write(qaa,store=qa,type=listing) 

%output(qab)
proc print;
format thedate yymmdd10. thetime time8.
  sasdt datetime.;
  
%endoutput(qab)

%write(qabb,store=qab,type=listing) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/hospital.csv";
proc import
  datafile=myurl
    dbms=csv
    out=stays
    replace;
  getnames=yes;

data hospitalstay;
  set stays;
  stay=(discharge-admit)/60/60/24;


%output(dq)
proc print;
    
%endoutput(dq)

%write(dqq,store=dq,type=listing) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/many.txt";
proc import
  datafile=myurl
    dbms=dlm out=many replace;
  delimiter=' ';
  getnames=no;


%output(ma)
proc print;
  
%endoutput(ma)

%write(maa,store=ma,type=listing) 

data one;
  set many;
  array x_array VAR1-VAR6;
  do i=1 to 6;
    x=x_array[i];
    output;
  end;
  keep x;


%output(mb)
proc print;
    
%endoutput(mb)

%write(mbb,store=mb,type=listing) 

data two;
  set many;
  array xy_array VAR1-VAR6;
  do i=1 to 3;
    x=xy_array[2*i-1];
    y=xy_array[2*i];
    output;
  end;
  keep x y;


%output(mc)
proc print;
  
%endoutput(mc)

%write(mcc,store=mc,type=listing) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/pigs1.txt";
libname mydata V9 '/home/ken';
proc import
  datafile=myurl
    dbms=dlm
    out=mydata.pigs1
    replace;
  delimiter=' ';
  getnames=yes;

%output(md)
proc means data='/home/ken/pigs1';
    
%endoutput(md)

%write(mdd,store=md,type=listing) 

%output(sozip)
proc print data=two;
    
%endoutput(sozip)

%write(sozipp,store=sozip,type=listing) 

libname mydata V9 '/home/ken';
data mydata.three; /* permanent data set to save in */
  set two; /* this has variables x and y in it */
  z=x+y;


%output(me)
proc print data='/home/ken/three';
    
%endoutput(me)

%write(mee,store=me,type=listing) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/ais.txt";
proc import
  datafile=myurl
  dbms=dlm
  out=sports
  replace;
  delimiter='09'x;
  getnames=yes;


%output(mix)
proc sgplot;
  histogram Ht;
  density Ht / type=kernel;

%endoutput(mix)

%write(mixx,store=mix,type=graphic) 

%output(miy)
proc sgplot;
  histogram BMI;
  density BMI / type=kernel;

%endoutput(miy)

%write(miyy,store=miy,type=graphic) 

%output(mjc)
proc sgplot;
  scatter x=Ht y=Wt;
  loess x=Ht y=Wt;

%endoutput(mjc)

%write(mjcc,store=mjc,type=graphic) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/windmill.csv";
proc import
  datafile=myurl
    dbms=csv
    out=windmill
    replace;
  getnames=yes;


%output(ng)
proc means;
  
%endoutput(ng)

%write(ngg,store=ng,type=listing) 

%output(mje)
proc sgplot;
  scatter x=wind_velocity y=DC_output;
  loess x=wind_velocity y=DC_output;

%endoutput(mje)

%write(mjee,store=mje,type=graphic) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/oranges.txt";
proc import
  datafile=myurl
    dbms=dlm
    out=trees
    replace;
  delimiter=' ';
  getnames=yes;


%output(ora)
proc print;
  
%endoutput(ora)

%write(oraa,store=ora,type=listing) 

%output(mjd)
proc sgplot;
  series x=age y=a / markers;
  series x=age y=b / markers;
  series x=age y=c / markers;
  series x=age y=d / markers;
  series x=age y=e / markers;

%endoutput(mjd)

%write(mjdd,store=mjd,type=graphic) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/cars.csv";
proc import
  datafile=myurl
  dbms=csv
  out=cars
  replace;
  getnames=yes;


%output(muggins)
proc sgplot;
  scatter y=mpg x=weight / datalabel=car;
    
%endoutput(muggins)

%write(mugginss,store=muggins,type=graphic) 

%output(mka)
proc sgplot;
  scatter x=weight y=mpg / datalabel=country;
  
%endoutput(mka)

%write(mkaa,store=mka,type=graphic) 

data cars2;
  set cars;
  if (_n_=4 or _n_=9) then do;
    newtext=car;
  end;


%output(mwa)
proc sgplot;
  scatter x=weight y=mpg / datalabel=newtext;
    
%endoutput(mwa)

%write(mwaa,store=mwa,type=graphic) 

data cars3;
  set cars;
  if mpg>34 then do;
     newtext=car;
  end;



%output(mjk)
proc sgplot;
  scatter x=weight y=mpg / datalabel=newtext;
  
%endoutput(mjk)

%write(mjkk,store=mjk,type=graphic) 

%output(ima)
proc iml;
  k=2;
  u={2 3 6 5 7};
  ans=k+u;
  print ans;
    
%endoutput(ima)

%write(imaa,store=ima,type=listing) 

%output(imb)
proc iml;
  u={2 3 6 5 7};
  v={1 8 3 4 2};
  ans=u+v;
  print ans;
    
%endoutput(imb)

%write(imbb,store=imb,type=listing) 

%output(imc)
proc iml;
  k=2;
  u={2 3 6 5 7};
  ans=k*u;
  print ans;
    
%endoutput(imc)

%write(imcc,store=imc,type=listing) 

%output(imea)
proc iml;
  A={1 3,2 4};
  B={5 6,7 8};
  print A;
  print B;
    
%endoutput(imea)

%write(imeaa,store=imea,type=listing) 

%output(ime)
proc iml;
  A={1 3,2 4};
  B={5 6,7 8};
  ans1=A+B;
  print ans1;
  ans2=A*B;
  print ans2;
    
%endoutput(ime)

%write(imee,store=ime,type=listing) 

filename myurl url
  "http://www.utsc.utoronto.ca/~butler/c32/m.txt";
proc import
  datafile=myurl
    dbms=dlm
    out=mymatrix
    replace;
  delimiter=' ';
  getnames=no;


%output(imf)
proc iml;
  use mymatrix;
  read all var {VAR1 VAR2} into M;
  v={1,3};
  ans=M*v;
  print ans;
    
%endoutput(imf)

%write(imff,store=imf,type=listing) 

%output(img)
proc iml;
  A={1 3,2 4};
  w={1,2};
  Ainv=inv(A);
  print Ainv;
  ans=Ainv*w;
  print ans;
    
%endoutput(img)

%write(imgg,store=img,type=listing) 

%output(imh)
proc iml;
  r={1 2 3};
  c={4,5,6};
  print r;
  print c;
    
%endoutput(imh)

%write(imhh,store=imh,type=listing) 

%output(imi)
proc iml;
  a={1,2,3};
  b={4,5,6};
  ans=t(a)*b;
  print ans;
    
%endoutput(imi)

%write(imii,store=imi,type=listing) 

